### ISSUE TITLE
Make svglib/reportlab/pillow extra dependencies?

### ISSUE THREAD

**Issue by deeplook** [cloudagon/simpleicons#3]
Just discovered this nice tool! If I see that correctly svglib, reportlab and pillow are only used when converting to bitmaps, right? As these are pretty heavy dependencies (I know because I'm the original author of [svglib](https://github.com/deeplook/svglib) ;) one might consider declaring them ["extra" dependencies](https://www.python.org/dev/peps/pep-0508/#extras) for pip. But I'm not familiar with poetry to know if it supports that.

**Comment by cloudagon** [comment]
Great idea, I'll get that published soon! Also I'm almost certain I'm not using these packages correctly [here](https://github.com/cloudagon/simpleicons/blob/main/simpleicons/image.py). My intent to to convert xml (bytes returned from [this function](https://github.com/cloudagon/simpleicons/blob/main/simpleicons/icon.py#L58)) to a PIL Image. I'm uncertain on how svglib and reportlab work, but seeing as you're the author of svglib, perhaps you could help here?

**Comment by deeplook** [comment]
> Also I'm almost certain I'm not using these packages correctly [here](https://github.com/cloudagon/simpleicons/blob/main/simpleicons/image.py). My intent to to convert xml (bytes returned from [this function](https://github.com/cloudagon/simpleicons/blob/main/simpleicons/icon.py#L58)) to a PIL Image. I'm uncertain on how svglib and reportlab work, but seeing as you're the author of svglib, perhaps you could help here?

That looks pretty good to me. What makes you doubt you're doing the right thing?

**Comment by cloudagon** [comment]
Not sure...using BytesIO always feels a little hacky to me.
